/**
 * @packageDocumentation
 * @module api.functional.hello
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection, Primitive } from "@nestia/fetcher";

/**
 * @controller AppController.getHello()
 * @path GET /hello
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getHello(
    connection: IConnection,
): Promise<getHello.Output> {
    return Fetcher.fetch(
        connection,
        getHello.ENCRYPTED,
        getHello.METHOD,
        getHello.path(),
    );
}
export namespace getHello {
    export type Output = Primitive<string>;

    export const METHOD = "GET" as const;
    export const PATH: string = "/hello";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export const path = (): string => {
        return `/hello`;
    }
}