/**
 * @packageDocumentation
 * @module api.functional.jsondata
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection, Primitive } from "@nestia/fetcher";

import type { User } from "./../../../user.types";

/**
 * @controller AppController.getJsonData()
 * @path GET /jsondata
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getJsonData(
    connection: IConnection,
): Promise<getJsonData.Output> {
    return Fetcher.fetch(
        connection,
        getJsonData.ENCRYPTED,
        getJsonData.METHOD,
        getJsonData.path(),
    );
}
export namespace getJsonData {
    export type Output = Primitive<Array<User>>;

    export const METHOD = "GET" as const;
    export const PATH: string = "/jsondata";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export const path = (): string => {
        return `/jsondata`;
    }
}